### PR TITLE
Implement gethostname

### PR DESCRIPTION
**Pull request by tomasol**
See #29 .
I could add a test that would compare the result with what `hostname` returns, if so, where should I place it?

### CODE REVIEW

**Comment by tomasol** [comment]
Currently it works on linux and windows, I will test it on mac tomorrow.
On windows side it uses environemnt variable, I was not able to figure out calling this function:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724295(v=vs.85).aspx

**Comment by tomasol** [comment]
ok it works now on linux (gethostname), mac os x(gethostname), windows(env.variable)

**Comment by nirvdrum** [comment]
Sorry, I'm just now seeing this. Is there a reason to close it?

**Comment by tomasol** [comment]
Hi, I was under impression this is not needed as there was no activity in this thread. I can rebase the commits if there is interest.

**Comment by nirvdrum** [comment]
Yeah, if you don't mind. I'll take a look at merging and look at handling Win32 a bit more cleanly.

**Comment by headius** [comment]
@nirvdrum Looking to do a release today. Can we merge this?

**Comment by headius** [comment]
Delaying until after 3.0.28.

**Comment by headius** [comment]
@nirvdrum @tomasol Bumping this to next release to get out other fixes. Still interested in pulling it in.

**Comment by nirvdrum** [comment]
I haven't forgotten about this one. I just want to work through the Win32 API to get it working on Windows. I'll try to make some time around the holidays. I'll deal with updating to work with the latest jnr-posix.

**Comment by TobiX** [comment]
Can somebody close this? It was fixed with #129

**Comment by nirvdrum** [comment]
Thanks for handling this one @TobiX. I feel like a jerk for never getting back to this. But I'm glad there's something in place that works on *nix and Windows.

**Pull request closed without merging**
