### PR TITLE
Use reflection to get native file descriptors lazily on first access

### LINKED ISSUE #108: JavaLibCHelper emits illegal reflective access warnings on Java 9
JavaLibCHelper emits warnings on Java 9:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:...jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

```
$ java --illegal-access=warn ...  
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/home/eregon/code/java9-ws/truffleruby/mxbuild/dists/truffleruby.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/home/eregon/code/java9-ws/truffleruby/mxbuild/dists/truffleruby.jar) to field sun.nio.ch.FileChannelImpl.fd
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/home/eregon/code/java9-ws/truffleruby/mxbuild/dists/truffleruby.jar) to field java.io.FileDescriptor.fd
```

The first two are only used by `getDescriptorFromChannel()` which is only used in tests.
Maybe we can just make that a private helper for tests? But not sure if somebody actually uses this helper.

The last one (`FileDescriptor.fd`) is used in tests but also for `fstat()` and other libc functions taking a FileDescriptor.

What would be a good option to fix these warnings?
I am thinking maybe just check for Java 9 and in such a case just set them to `null` as if there was a SecurityException.
Or maybe move those in a separate class so they only load on first usage.
In the case of TruffleRuby, we have fds as `int` so these methods taking `FileDescriptor` instances are never used I believe.

cc @headius @chrisseaton

### PR DESCRIPTION
**Pull request by eregon**
* As it creates warnings on Java 9.
* Fixes #108.

### CODE REVIEW

**Comment by headius** [comment]
I may be missing the key change here, but why does this work? After a couple readthroughs all I can see is that you moved the static fields + init into a static inner class. That avoids the warnings how?

**Comment by eregon** [comment]
@headius It avoids the warnings in the case these fields are not accessed at runtime. This reflection is only needed for a couple cases listed in #108 (tests and functions taking a FileDescriptor) and we actually don't use them at all in TruffleRuby.
For JRuby, this will also fix the warnings if e.g. fstat(FileDescriptor) is not used. I don't know of any workaround possible if that usage is needed.
So at least it delays the warning until the first usage that actually needs it, instead of warning when loading jnr-posix.

**Comment by headius** [comment]
@eregon Ahh I see, by moving them into a static inner class the lazy booting of classes prevents the initialization until we actually call those reflecting utility methods.

Ok, merging.

**Comment by eregon** [comment]
Yes, I should have added a comment to clarify in the code.
I can do that in another PR if you'd like.

**Pull request merged**
