### PR TITLE
Support for LoongArch64

### PR DESCRIPTION
**Pull request by Panxuefeng-loongson**

### CODE REVIEW

**Comment by Panxuefeng-loongson** [comment]
I tested as you suggested, I found that LoongArch support should be added in this repo. I ran tests on the changes and one test failed, I don't  know how to fix this failure, can you give me some advice？
```
Tests run: 32, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.481 sec <<< FAILURE! - in jnr.posix.FileTest
readlinkPointerTest(jnr.posix.FileTest)  Time elapsed: 0.022 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:</tmp/jnr-p[?six-r??dl?nk-t?]st175907513659061277...> but was:</tmp/jnr-p[?six-r??dl?nk-t?]st175907513659061277...>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at jnr.posix.FileTest.readlinkPointerTest(FileTest.java:590)

```

**Comment by headius** [comment]
Back to this again... I have enabled the actions to run on this PR. I'm not sure what is up with that failure but it doesn't seem to be critical right now. I can merge this and get a release out soon and we'll look into that failure separately.

**Comment by Panxuefeng-loongson** [comment]
Good news! Thanks

**Comment by Panxuefeng-loongson** [comment]
@headius  I just looked at it, and if LoongArch is supported, the jruby code doesn't seem to need a lot of changes. When I have time recently, I may commit LoongArch's changes to jruby first, and then verify the functionality when the new version of jnr is released.

**Comment by headius** [comment]
@Panxuefeng-loongson Sure, we can do this in parallel with PRs. I'm still working with @jcharaoui on getting some Debian patches merged into jffi so we can do a better release, but hopefully we'll get through that soon.

**Pull request merged**
