### PR TITLE
Add POSIX.daemon

### PR DESCRIPTION
**Pull request by bjfish**
Does this need a test to be merged? If so, any suggestions on how to test this?

### CODE REVIEW

**Comment by headius** [comment]
Does this even work? I believe `daemon` uses `fork`, and typical JVMs are not forkable (kinda hard to survive after you leave your GC threads behind).

**Comment by headius** [comment]
FWIW, I tried this with Ruby FFI. It only takes a few seconds for the process to die after demonization:

```ruby
module Daemon
  extend FFI::Library
  ffi_lib 'c'
  attach_function :daemon, [:int, :int], :int
end

Daemon.daemon(1, 1)

loop { puts Time.now; sleep 5 }"
```

Granted we do bind `fork` knowing it doesn't work :-)

**Comment by bjfish** [comment]
@headius I ran your example following result. It looks like the expected result to me. I'm on Mac OSX and you?
```
Brandons-MacBook-Pro:jruby brandonfish$ ./bin/jruby ../jruby-patches/daemon.rb 
Brandons-MacBook-Pro:jruby brandonfish$ 2016-09-08 08:43:26 -0500
2016-09-08 08:43:31 -0500
2016-09-08 08:43:36 -0500
2016-09-08 08:43:41 -0500
2016-09-08 08:43:46 -0500
2016-09-08 08:43:51 -0500
2016-09-08 08:43:56 -0500
```

**Comment by headius** [comment]
It runs for a while, but I guarantee it dies eventually.

screenshot 2016-09-08 21 07 29

Note only one thread. No JIT, no signal handling, no GC.

Remove the sleep to speed up the failure:
```
[] ~/projects/jruby $ jruby blah.rb

[] ~/projects/jruby $ 2016-09-08 21:09:13 -0500
2016-09-08 21:09:13 -0500
2016-09-08 21:09:13 -0500
2016-09-08 21:09:13 -0500
2016-09-08 21:09:13 -0500
2016-09-08 21:09:13 -0500
2016-09-08 21:09:13 -0500
...
2016-09-08 21:09:16 -0500
2016-09-08 21:09:16 -0500
2016-09-08 21:09:16 -0500
2016-09-08 21:09:16 -0500
2016-09-08 21:09:16 -0500
```

There's no further output after this point. The single-thread java process remains but appears to be frozen...probably waiting for the lost GC or JIT to run.

I want to be clear: I'm not opposed to merging this, since there may be JVMs out there that are daemon-friendly (Android's, JamVM and other small JVMs maybe). I just want to make it clear it doesn't work properly on any OpenJDK-based JVM. If it did, we'd have supported daemonization a long time ago :-)

**Comment by bjfish** [comment]
@headius Thanks for clarifying this!

**Comment by headius** [comment]
Given that we already bind fork, I think we can merge this. Given that we have no JVM handy on which we can reliably test it, I think we can forgo the test for now.

**Pull request merged**
